// Generated by Wrangler by running `wrangler types`

interface Env {
	PUBLIC_SITE_URL: string;
	PUBLIC_API_URL: string;
	TELEGRAM_BOT_TOKEN: string;
	TELEGRAM_CHAT_ID: string;
	PUBLIC_TURNSTILE_SITE_KEY: string;
	TURNSTILE_SECRET_KEY: string;
}
