interface Review {
  id: string;
  carId: string;
  avatarUrl: string;
  rating: number;
  fullName: string;
  text: string;
}

export const getList = async ({
  carId,
  locale,
}: {
  carId: string;
  locale: "en" | "ru";
}): Promise<Review[]> => {
  const ru: Review[] = [
    {
      id: "832688",
      carId: "019266fe-0883-7bb4-b7d7-90d3a9148306",
      avatarUrl: "https://example.com/avatar/68.png",
      rating: 4,
      fullName: "Иван Иванов",
      text: "Арендовал машину на Пхукете для поездок по острову. Очень удобная, легко парковаться в узких местах и быстро ехать по серпантинам. Однако, на длинные поездки хотелось бы немного больше комфорта в салоне.",
    },
    {
      id: "609186",
      carId: "019266fe-0883-7bb4-b7d7-90d3a9148306",
      avatarUrl: "https://example.com/avatar/82.png",
      rating: 5,
      fullName: "Сергей Морозов",
      text: "Отличная машина для аренды на Пхукете! Удобно перемещаться между пляжами, вместительная для всех вещей и едет плавно. Без проблем проехал все маршруты, включая горные дороги.",
    },
    {
      id: "485263",
      carId: "019266fe-0883-7bb4-b7d7-90d3a9148306",
      avatarUrl: "https://example.com/avatar/12.png",
      rating: 4,
      fullName: "Екатерина Лебедева",
      text: "Арендовали эту машину для семейного отдыха на Пхукете. Всё понравилось: машина экономичная, есть всё необходимое, но хотелось бы чуть больше мощности на крутых подъемах.",
    },
    {
      id: "774325",
      carId: "019266fe-0883-7bb4-b7d7-90d3a9148306",
      avatarUrl: "https://example.com/avatar/45.png",
      rating: 5,
      fullName: "Дмитрий Алексеев",
      text: "Брали в аренду на три дня для поездок по Пхукету. Машина идеально подходит для небольших поездок по городу и пляжам. Никаких нареканий, очень удобная и экономичная!",
    },
    {
      id: "301278",
      carId: "019266fe-0883-7bb4-b7d7-90d3a9148306",
      avatarUrl: "https://example.com/avatar/19.png",
      rating: 5,
      fullName: "Анастасия Белова",
      text: "Замечательная машина для отдыха на Пхукете. Мы арендовали её на неделю, и она отлично справилась с любой дорогой, будь то городские улицы или дороги к отдаленным пляжам.",
    },
    //
    {
      id: "581254",
      carId: "019266fe-15ed-7aa5-a6ae-3d29548c2c28",
      avatarUrl: "https://example.com/avatar/25.png",
      rating: 5,
      fullName: "Ольга Петрова",
      text: "Прекрасная машина для поездок по Пхукету. Взяли её на неделю, ездили на пляжи и по горам. Все было отлично, удобная и надежная, особенно понравилась плавность хода на длинных участках дороги.",
    },
    {
      id: "773058",
      carId: "019266fe-15ed-7aa5-a6ae-3d29548c2c28",
      avatarUrl: "https://example.com/avatar/74.png",
      rating: 4,
      fullName: "Александр Кузнецов",
      text: "Арендовали машину на Пхукете для поездок по городу и в соседние деревни. Удобная и маневренная, но иногда хотелось бы больше мощности на подъемах. В остальном — отличный выбор для аренды.",
    },
    {
      id: "306275",
      carId: "019266fe-15ed-7aa5-a6ae-3d29548c2c28",
      avatarUrl: "https://example.com/avatar/96.png",
      rating: 5,
      fullName: "Мария Смирнова",
      text: "Идеальная машина для аренды на Пхукете! Ездили по всему острову, и никаких проблем с автомобилем не возникло. Легко справляется как с городскими улицами, так и с горными дорогами. Рекомендую!",
    },
    //
    {
      id: "962841",
      carId: "019266fe-26a4-7dda-b2fb-081f4408fe85",
      avatarUrl: "https://example.com/avatar/54.png",
      rating: 5,
      fullName: "Андрей Соколов",
      text: "Арендовал Toyota Yaris Cross на Пхукете для поездок по острову. Машина просто отличная! Легко справляется с местными горными дорогами, достаточно мощная для всех подъемов. Удобно и комфортно как в городе, так и на пляжных маршрутах.",
    },
    {
      id: "481206",
      carId: "019266fe-26a4-7dda-b2fb-081f4408fe85",
      avatarUrl: "https://example.com/avatar/67.png",
      rating: 4,
      fullName: "Елена Воробьева",
      text: "Арендовали Toyota Yaris Cross на Пхукете для семейных поездок. Машина вместительная и экономичная, что особенно понравилось. Единственный минус — это немного жесткая подвеска на ухабистых дорогах, но в целом впечатления отличные.",
    },
    {
      id: "712903",
      carId: "019266fe-26a4-7dda-b2fb-081f4408fe85",
      avatarUrl: "https://example.com/avatar/81.png",
      rating: 5,
      fullName: "Максим Ковалев",
      text: "Toyota Yaris Cross оказалась идеальной для поездок по Пхукету. Взяли её на неделю, объехали весь остров, и она показала себя с лучшей стороны. Компактная, но просторная внутри, очень удобно было перемещаться по узким улицам и серпантинам.",
    },
    {
      id: "395284",
      carId: "019266fe-26a4-7dda-b2fb-081f4408fe85",
      avatarUrl: "https://example.com/avatar/31.png",
      rating: 4,
      fullName: "Дарья Тихонова",
      text: "Мы арендовали Toyota Yaris Cross на Пхукете и остались довольны. Машина отлично ведет себя на дороге, особенно понравилось, как она справляется с крутыми поворотами. Было бы идеально, если бы она немного мягче проходила неровности дороги.",
    },
    //
    {
      id: "857193",
      carId: "019266fe-33ab-7229-b577-09da52f3d238",
      avatarUrl: "https://example.com/avatar/22.png",
      rating: 5,
      fullName: "Алексей Григорьев",
      text: "Toyota Veloz — отличная машина для семейных поездок по Пхукету. Взяли её на несколько дней, и она оказалась невероятно просторной и удобной. Хорошо идет по серпантинам, много места для вещей и пассажиров. Идеальный выбор для большой семьи.",
    },
    {
      id: "649284",
      carId: "019266fe-33ab-7229-b577-09da52f3d238",
      avatarUrl: "https://example.com/avatar/33.png",
      rating: 4,
      fullName: "Ирина Самойлова",
      text: "Мы арендовали Toyota Veloz на время отпуска на Пхукете. Машина комфортная, много места, особенно для вещей после шопинга. Единственное, хотелось бы немного больше мощности на крутых горных дорогах, но в целом машина оправдала ожидания.",
    },
    {
      id: "312098",
      carId: "019266fe-33ab-7229-b577-09da52f3d238",
      avatarUrl: "https://example.com/avatar/88.png",
      rating: 5,
      fullName: "Олег Смирнов",
      text: "Арендовали Toyota Veloz на Пхукете для поездок с друзьями. Очень просторная, идеально подходила для поездок по острову. Даже на узких улицах управляется легко, все остались довольны. Плюс, машина новая и в отличном состоянии!",
    },
    //
    {
      id: "486923",
      carId: "019266fe-496b-7bb9-9b3a-94730439c6d7",
      avatarUrl: "https://example.com/avatar/45.png",
      rating: 5,
      fullName: "Сергей Иванов",
      text: "Toyota Fortuner — это просто находка для поездок по Пхукету! Мы арендовали этот внедорожник на неделю и он отлично справлялся с любыми дорогами — от пляжей до горных трасс. Очень комфортный салон и достаточно мощный двигатель для любых условий.",
    },
    {
      id: "729184",
      carId: "019266fe-496b-7bb9-9b3a-94730439c6d7",
      avatarUrl: "https://example.com/avatar/67.png",
      rating: 5,
      fullName: "Анна Кузнецова",
      text: "Мы были в восторге от Toyota Fortuner! Машина большая, вместительная, и идеально подходит для семейных поездок по Пхукету. Плавно идет по неровным дорогам, с комфортом ездили и по пляжам, и по горным серпантинам. Однозначно рекомендую для аренды.",
    },
    {
      id: "537620",
      carId: "019266fe-496b-7bb9-9b3a-94730439c6d7",
      avatarUrl: "https://example.com/avatar/74.png",
      rating: 4,
      fullName: "Дмитрий Федоров",
      text: "Взяли Toyota Fortuner для путешествий по Пхукету, и он оправдал все ожидания. Машина мощная и надежная, легко справляется с подъемами и пересеченной местностью. Единственный минус — расход топлива, но для внедорожника это нормально.",
    },
    //
    {
      id: "198237",
      carId: "019266fe-5670-7aaf-b539-b4fa8ca11661",
      avatarUrl: "https://example.com/avatar/82.png",
      rating: 5,
      fullName: "Виктория Орлова",
      text: "Арендовали новый Toyota Fortuner 2023 на Пхукете — невероятно комфортная и мощная машина. Проехали по всему острову, и не было ни одного участка дороги, который бы её остановил. Новый салон с современными опциями — просто супер!",
    },
    {
      id: "645820",
      carId: "019266fe-5670-7aaf-b539-b4fa8ca11661",
      avatarUrl: "https://example.com/avatar/61.png",
      rating: 5,
      fullName: "Денис Рябов",
      text: "Новейший Toyota Fortuner 2023 — это топ! Взяли его для путешествия по Пхукету, и машина не разочаровала. Очень комфортная, с отличной подвеской, которая легко справлялась с местными дорогами. Удобные современные системы помощи водителю.",
    },
    {
      id: "731952",
      carId: "019266fe-5670-7aaf-b539-b4fa8ca11661",
      avatarUrl: "https://example.com/avatar/52.png",
      rating: 4,
      fullName: "Кирилл Захаров",
      text: "Toyota Fortuner 2023 показал себя великолепно на дорогах Пхукета. Очень мощный внедорожник, идеален для горных серпантинов и пляжей. Единственный минус — немного высокий расход топлива, но это ожидаемо для такой мощной машины.",
    },
    //
    {
      id: "582940",
      carId: "019266fe-6242-7770-a53f-3f4e1b43a186",
      avatarUrl: "https://example.com/avatar/49.png",
      rating: 5,
      fullName: "Максим Лебедев",
      text: "Toyota Hilux 2022 — идеальный вариант для приключений на Пхукете! Четырехдверный кузов дает много места для пассажиров, а мощный двигатель отлично справляется с любыми дорогами. Мы ездили по пляжам, горным тропам — машина не подвела ни разу.",
    },
    {
      id: "731004",
      carId: "019266fe-6242-7770-a53f-3f4e1b43a186",
      avatarUrl: "https://example.com/avatar/60.png",
      rating: 4,
      fullName: "Татьяна Смирнова",
      text: "Арендовали Toyota Hilux на время отпуска на Пхукете. Просторный, вместительный салон, удобен для всей семьи. Машина легко справляется с крутыми подъемами и неровными дорогами. Единственное — машина большая, парковка иногда была сложной.",
    },
    {
      id: "894572",
      carId: "019266fe-6242-7770-a53f-3f4e1b43a186",
      avatarUrl: "https://example.com/avatar/71.png",
      rating: 5,
      fullName: "Ольга Крылова",
      text: "Toyota Hilux — это мощь и комфорт в одном флаконе! Просторный четырехдверный кузов оказался очень удобным для нашей компании, а проходимость автомобиля удивила — он легко справлялся с пляжами и бездорожьем Пхукета. Очень рекомендую для активного отдыха.",
    },
    //
    {
      id: "348291",
      carId: "019266fe-6dfc-7669-8679-b73735fc4bb6",
      avatarUrl: "https://example.com/avatar/27.png",
      rating: 5,
      fullName: "Ирина Соколова",
      text: "Арендовала Honda Jazz 2024 во время отпуска на Пхукете, и была в полном восторге! Машина очень маневренная и экономичная. Отлично подходит для городских поездок и исследовательских поездок по острову. Интерьер приятный и современный, все на своем месте.",
    },
    {
      id: "249058",
      carId: "019266fe-6dfc-7669-8679-b73735fc4bb6",
      avatarUrl: "https://example.com/avatar/34.png",
      rating: 4,
      fullName: "Александр Петров",
      text: "Honda Jazz 2024 оказалась отличным выбором для поездок по Пхукету. Просторный салон для маленького хэтчбека и хороший багажник. Машина достаточно быстрая и легкая в управлении. Единственное, в ней немного шумно на высоких скоростях.",
    },
    {
      id: "615083",
      carId: "019266fe-6dfc-7669-8679-b73735fc4bb6",
      avatarUrl: "https://example.com/avatar/12.png",
      rating: 5,
      fullName: "Екатерина Ларионова",
      text: "Просто обожаю Honda Jazz 2024! Взяла её в аренду на Пхукете, и это было лучшее решение. Компактная, экономичная и с отличной управляемостью. Понравились современные функции безопасности и удобные сиденья. Рекомендую всем, кто планирует поездки по городу!",
    },
    //
    {
      id: "415890",
      carId: "019266fe-7b7d-7bbd-888c-d6710e499c1e",
      avatarUrl: "https://example.com/avatar/75.png",
      rating: 5,
      fullName: "Наталья Фомина",
      text: "Арендовала Honda City 2024 на Пхукете, и она превзошла все ожидания! Белый цвет машины выглядит шикарно, а внутри всё чисто и аккуратно. Отличная управляемость и экономичный расход топлива. Идеальный выбор для городских поездок!",
    },
    {
      id: "382047",
      carId: "019266fe-7b7d-7bbd-888c-d6710e499c1e",
      avatarUrl: "https://example.com/avatar/90.png",
      rating: 4,
      fullName: "Дмитрий Ковалев",
      text: "Honda City 2024 очень комфортная и стильная. Мы взяли её в аренду на Пхукете, и она отлично справилась со всеми местными дорогами. Просторный салон и современное оборудование — всё это сделало наши поездки очень приятными. Немного шумно на скорости, но в целом, всё супер.",
    },
    {
      id: "563802",
      carId: "019266fe-7b7d-7bbd-888c-d6710e499c1e",
      avatarUrl: "https://example.com/avatar/44.png",
      rating: 5,
      fullName: "Игорь Степанов",
      text: "Просто в восторге от Honda City! Взял её на время отпуска на Пхукете, и она была в отличном состоянии. Удобные сиденья, хорошая звукоизоляция и современные технологии делают её идеальным автомобилем для путешествий. Обязательно вернусь за ней снова!",
    },
    //
    {
      id: "724150",
      carId: "019266fe-86ad-7ee6-8574-8dbecc893f41",
      avatarUrl: "https://example.com/avatar/11.png",
      rating: 5,
      fullName: "Светлана Новикова",
      text: "Арендовала Honda Accord 2024 на Пхукете, и это была лучшая машина для моего отпуска! Она выглядит стильно и современно, а внутри просто шикарно. Очень удобные сиденья и много места для багажа. Это идеальный автомобиль для длительных поездок по острову.",
    },
    {
      id: "842607",
      carId: "019266fe-86ad-7ee6-8574-8dbecc893f41",
      avatarUrl: "https://example.com/avatar/29.png",
      rating: 4,
      fullName: "Анатолий Павлов",
      text: "Honda Accord 2024 — отличный выбор! Сильно впечатлён её производительностью и комфортом. На Пхукете она отлично справляется с дорогами. Единственное, что хотелось бы улучшить — это немного больше места в заднем ряду. В остальном, всё прекрасно!",
    },
    {
      id: "593718",
      carId: "019266fe-86ad-7ee6-8574-8dbecc893f41",
      avatarUrl: "https://example.com/avatar/88.png",
      rating: 5,
      fullName: "Елена Мартынова",
      text: "Потрясающая машина! Honda Accord 2024 просто великолепна. Удобная и тихая при движении. Мы путешествовали по Пхукету, и она была надежным спутником. Очень рекомендую для тех, кто хочет наслаждаться поездками без лишних забот!",
    },
    //
    {
      id: "473190",
      carId: "019266fe-91d2-7881-8a8d-2998ffbf7d59",
      avatarUrl: "https://example.com/avatar/37.png",
      rating: 5,
      fullName: "Мария Сидорова",
      text: "Арендовала Honda HRV 2024 на Пхукете, и это был отличный выбор! Машина стильная, комфортная и очень удобная для поездок по острову. Высокий клиренс позволяет легко справляться с местными дорогами. Рекомендую всем, кто ищет надежный паркетник!",
    },
    {
      id: "639582",
      carId: "019266fe-91d2-7881-8a8d-2998ffbf7d59",
      avatarUrl: "https://example.com/avatar/48.png",
      rating: 4,
      fullName: "Олег Зайцев",
      text: "Honda HRV 2024 оказалась отличным автомобилем для путешествий по Пхукету. Просторный салон и хорошая вместимость багажника. Понравилась высокая посадка и отличная видимость. Немного жестковатая подвеска, но в целом, это не испортило впечатление.",
    },
    {
      id: "918302",
      carId: "019266fe-91d2-7881-8a8d-2998ffbf7d59",
      avatarUrl: "https://example.com/avatar/92.png",
      rating: 5,
      fullName: "Иван Кузнецов",
      text: "Просто супер! Honda HRV 2024 — это идеальный паркетник для поездок по Пхукету. Машина в отличном состоянии, много современных функций и комфортный интерьер. Мы с семьей провели отличное время, и HRV стал для нас надежным партнером на дороге!",
    },
    //
    {
      id: "392481",
      carId: "019266fe-9df5-777c-a3b5-c6ba339d131d",
      avatarUrl: "https://example.com/avatar/12.png",
      rating: 5,
      fullName: "Анна Соколова",
      text: "Арендовала MG5 на Пхукете, и он стал идеальным спутником в моем отпуске! Машина выглядит очень стильно, особенно в белом цвете. Удобный салон и отличная управляемость. Я была в восторге от каждой поездки!",
    },
    {
      id: "824159",
      carId: "019266fe-9df5-777c-a3b5-c6ba339d131d",
      avatarUrl: "https://example.com/avatar/55.png",
      rating: 4,
      fullName: "Сергей Романов",
      text: "MG5 — отличный выбор! На Пхукете он показал себя с лучшей стороны. Просторный и комфортабельный салон, много места для багажа. Но немного не хватало мощности на обгонах. В целом, очень доволен арендой!",
    },
    {
      id: "467891",
      carId: "019266fe-9df5-777c-a3b5-c6ba339d131d",
      avatarUrl: "https://example.com/avatar/74.png",
      rating: 5,
      fullName: "Екатерина Федорова",
      text: "Прекрасный автомобиль! MG5 был в отличном состоянии и стал для нас надежным другом на Пхукете. Стильный внешний вид и комфортный интерьер. Я бы снова выбрала его для поездок по острову!",
    },
    {
      id: "579430",
      carId: "019266fe-9df5-777c-a3b5-c6ba339d131d",
      avatarUrl: "https://example.com/avatar/26.png",
      rating: 4,
      fullName: "Дмитрий Семенов",
      text: "MG5 очень стильный и современный. Мы арендовали его на Пхукете и были довольны. Отличное управление и экономичный расход топлива. Единственное — хотелось бы более мощный двигатель для активной езды.",
    },
    {
      id: "753210",
      carId: "019266fe-9df5-777c-a3b5-c6ba339d131d",
      avatarUrl: "https://example.com/avatar/83.png",
      rating: 5,
      fullName: "Татьяна Васильева",
      text: "MG5 стал настоящей находкой в нашем отпуске на Пхукете! Стильный и современный, он привлекал внимание всех вокруг. Очень удобен в управлении и прекрасно подходит для поездок по острову. Рекомендую всем!",
    },
    //
    {
      id: "782301",
      carId: "019266fe-ab44-7bbe-acd8-e3776d5ae6f8",
      avatarUrl: "https://example.com/avatar/13.png",
      rating: 5,
      fullName: "Алексей Петров",
      text: "Арендовал Mazda 2 на Пхукете — это была отличная идея! Машина очень удобная, идеально подходит для города. Отличная управляемость и экономичный расход топлива сделали поездки приятными. Рекомендую всем!",
    },
    {
      id: "894561",
      carId: "019266fe-ab44-7bbe-acd8-e3776d5ae6f8",
      avatarUrl: "https://example.com/avatar/25.png",
      rating: 4,
      fullName: "Светлана Николаева",
      text: "Mazda 2 — это отличный городской автомобиль! Удобный и компактный, она прекрасно справляется с местными пробками. Единственное, не хватает немного мощности на высоких скоростях, но в целом впечатления положительные.",
    },
    {
      id: "652134",
      carId: "019266fe-ab44-7bbe-acd8-e3776d5ae6f8",
      avatarUrl: "https://example.com/avatar/37.png",
      rating: 5,
      fullName: "Игорь Михайлов",
      text: "Наша семья арендовала Mazda 2 на время отпуска, и это был лучший выбор! Просторный салон, комфортные сиденья и отличный звук. Мы с удовольствием катались по красивым местам Пхукета!",
    },
    {
      id: "312567",
      carId: "019266fe-ab44-7bbe-acd8-e3776d5ae6f8",
      avatarUrl: "https://example.com/avatar/49.png",
      rating: 4,
      fullName: "Ольга Сергеева",
      text: "Mazda 2 понравилась своей компактностью и удобством. Она отлично подходит для городских поездок на Пхукете. Машина новая, в идеальном состоянии. Хотелось бы немного больше места для багажа, но в остальном все супер.",
    },
    {
      id: "849320",
      carId: "019266fe-ab44-7bbe-acd8-e3776d5ae6f8",
      avatarUrl: "https://example.com/avatar/56.png",
      rating: 5,
      fullName: "Виктория Коваленко",
      text: "Прекрасный выбор для аренды! Mazda 2 очень удобная и стильная. Мы путешествовали по Пхукету, и она отлично справилась с местными дорогами. Очень довольны качеством автомобиля!",
    },
    //
    {
      id: "473198",
      carId: "019266fe-b881-7550-9ff0-168bcbdc8cbf",
      avatarUrl: "https://example.com/avatar/14.png",
      rating: 5,
      fullName: "Анатолий Кузнецов",
      text: "Арендовал Mazda 3 на Пхукете, и это была отличная идея! Машина белого цвета выглядит просто шикарно. Комфортная, быстро реагирует на повороты, а управление просто на высоте. Очень рекомендую для поездок по острову!",
    },
    {
      id: "298346",
      carId: "019266fe-b881-7550-9ff0-168bcbdc8cbf",
      avatarUrl: "https://example.com/avatar/67.png",
      rating: 4,
      fullName: "Елена Григорьева",
      text: "Mazda 3 — отличный автомобиль для Пхукета! Удобная и современная, она очень хорошо держит дорогу. Единственное, хотелось бы больше места для задних пассажиров, но в остальном все супер!",
    },
    {
      id: "634829",
      carId: "019266fe-b881-7550-9ff0-168bcbdc8cbf",
      avatarUrl: "https://example.com/avatar/42.png",
      rating: 5,
      fullName: "Максим Зайцев",
      text: "Наша семья была в восторге от Mazda 3! Новый автомобиль, очень комфортный и с отличной аудиосистемой. Мы с удовольствием катались по красивым местам Пхукета, и ни разу не пожалели о выборе.",
    },
    {
      id: "859430",
      carId: "019266fe-b881-7550-9ff0-168bcbdc8cbf",
      avatarUrl: "https://example.com/avatar/58.png",
      rating: 4,
      fullName: "Ирина Васильева",
      text: "Mazda 3 — очень стильный и удобный автомобиль. На Пхукете она показала себя с лучшей стороны. Отличное управление и экономичный расход топлива. Немного не хватает пространства для багажа, но в целом очень хорошее впечатление.",
    },
    {
      id: "194625",
      carId: "019266fe-b881-7550-9ff0-168bcbdc8cbf",
      avatarUrl: "https://example.com/avatar/71.png",
      rating: 5,
      fullName: "Роман Сидоров",
      text: "Прекрасный автомобиль для аренды! Mazda 3 идеально подходит для поездок по Пхукету. Она красивая, надежная и комфортная. Мы не заметили никаких проблем во время использования. Рекомендую всем!",
    },
    //
    {
      id: "614720",
      carId: "019266fe-c64d-7008-ad72-f66ba0fcb72c",
      avatarUrl: "https://example.com/avatar/19.png",
      rating: 5,
      fullName: "Кирилл Смирнов",
      text: "Арендовали Mazda CX-30 на Пхукете — это был отличный выбор! Красный цвет автомобиля просто привлекает внимание. Очень комфортная и мощная, она прекрасно подходит для путешествий по живописным местам острова.",
    },
    {
      id: "128503",
      carId: "019266fe-c64d-7008-ad72-f66ba0fcb72c",
      avatarUrl: "https://example.com/avatar/22.png",
      rating: 4,
      fullName: "Мария Лебедева",
      text: "Mazda CX-30 оставила хорошие впечатления. Отличное сочетание стиля и комфорта! Удобно управлять, особенно на извивающихся дорогах Пхукета. Немного не хватало пространства для багажа, но в целом все понравилось.",
    },
    {
      id: "304892",
      carId: "019266fe-c64d-7008-ad72-f66ba0fcb72c",
      avatarUrl: "https://example.com/avatar/35.png",
      rating: 5,
      fullName: "Дмитрий Соловьев",
      text: "Мой опыт аренды Mazda CX-30 был потрясающим! Красный цвет просто шикарен. Автомобиль новый, полностью исправен и имеет отличные функции безопасности. Мы с удовольствием катались по острову и посещали все достопримечательности.",
    },
    {
      id: "592104",
      carId: "019266fe-c64d-7008-ad72-f66ba0fcb72c",
      avatarUrl: "https://example.com/avatar/46.png",
      rating: 4,
      fullName: "Александра Федорова",
      text: "Mazda CX-30 — отличный выбор для поездок по Пхукету! Удобные сиденья и современный интерьер делают путешествие приятным. Были некоторые мелкие проблемы с навигацией, но в целом это не испортило впечатление.",
    },
    {
      id: "843920",
      carId: "019266fe-c64d-7008-ad72-f66ba0fcb72c",
      avatarUrl: "https://example.com/avatar/53.png",
      rating: 5,
      fullName: "Валентин Егоров",
      text: "Восхитительная Mazda CX-30! Мы арендовали её на неделю на Пхукете и остались в полном восторге. Красивый внешний вид, прекрасная управляемость и высокая экономичность. Настоятельно рекомендую!",
    },
    //
    {
      id: "284630",
      carId: "019266fe-d711-788a-bfb9-ebe5d5ad8172",
      avatarUrl: "https://example.com/avatar/11.png",
      rating: 5,
      fullName: "Игорь Михайлов",
      text: "Арендовали BMW M5 на Пхукете — это было невероятно! Машина белого цвета выглядит просто роскошно. Удивительная мощность и управление. С ней каждое движение — удовольствие. Определенно рекомендую!",
    },
    {
      id: "374820",
      carId: "019266fe-d711-788a-bfb9-ebe5d5ad8172",
      avatarUrl: "https://example.com/avatar/29.png",
      rating: 4,
      fullName: "Светлана Петрова",
      text: "BMW M5 — это мечта! Мы провели незабываемое время на Пхукете. Единственное, что хотелось бы отметить — достаточно жесткая подвеска, но для спортивной машины это нормально. В остальном все было на высшем уровне!",
    },
    {
      id: "728105",
      carId: "019266fe-d711-788a-bfb9-ebe5d5ad8172",
      avatarUrl: "https://example.com/avatar/53.png",
      rating: 5,
      fullName: "Денис Орлов",
      text: "Не могу не поделиться своим восторгом от BMW M5! Белый цвет делает её еще более привлекательной. Удобно управлять, мощный двигатель и отличные характеристики. Поездки по Пхукету стали настоящим удовольствием!",
    },
    {
      id: "493271",
      carId: "019266fe-d711-788a-bfb9-ebe5d5ad8172",
      avatarUrl: "https://example.com/avatar/32.png",
      rating: 5,
      fullName: "Евгений Сухов",
      text: "Просто потрясающая машина! BMW M5 — это воплощение стиля и скорости. Мы ездили по всему Пхукету и наслаждались каждой минутой. Рекомендую всем, кто хочет получить незабываемые впечатления!",
    },
    {
      id: "826510",
      carId: "019266fe-d711-788a-bfb9-ebe5d5ad8172",
      avatarUrl: "https://example.com/avatar/47.png",
      rating: 4,
      fullName: "Наталья Ковалёва",
      text: "Аренда BMW M5 — это был прекрасный выбор для нашего отдыха на Пхукете. Отличная машина с высокой производительностью. Однако, стоит учитывать, что расход топлива выше среднего. В целом, все остались довольны!",
    },
    //
    {
      id: "594760",
      carId: "019266fe-e218-7556-862e-1a29c36d10d6",
      avatarUrl: "https://example.com/avatar/18.png",
      rating: 5,
      fullName: "Александр Романов",
      text: "Арендовали Toyota Vios на Пхукете, и она была в отличном состоянии! Это идеальный выбор для поездок по городу. Компактный размер, экономичный расход топлива и комфортная езда. Очень довольны!",
    },
    {
      id: "294835",
      carId: "019266fe-e218-7556-862e-1a29c36d10d6",
      avatarUrl: "https://example.com/avatar/21.png",
      rating: 4,
      fullName: "Елена Кузнецова",
      text: "Toyota Vios — отличный автомобиль для аренды на Пхукете! Мы впечатлены тем, в каком состоянии она находилась. Комфортабельная и надежная. Единственное, что не хватало немного мощности на трассе, но в городе она просто идеальна.",
    },
    {
      id: "832947",
      carId: "019266fe-e218-7556-862e-1a29c36d10d6",
      avatarUrl: "https://example.com/avatar/36.png",
      rating: 5,
      fullName: "Максим Тихонов",
      text: "Прекрасный опыт аренды Toyota Vios! Машина выглядела как новая, и управлять ей было легко и приятно. Идеально подходит для путешествий по Пхукету. Очень рекомендую тем, кто ищет надежный и экономичный автомобиль!",
    },
    {
      id: "583210",
      carId: "019266fe-e218-7556-862e-1a29c36d10d6",
      avatarUrl: "https://example.com/avatar/48.png",
      rating: 5,
      fullName: "Наталия Сергеева",
      text: "Мы с мужем арендовали Toyota Vios на две недели. Машина была в отличном состоянии, полностью исправна. Мы насладились поездками по Пхукету и получили массу положительных эмоций. Обязательно вернемся снова!",
    },
    {
      id: "947263",
      carId: "019266fe-e218-7556-862e-1a29c36d10d6",
      avatarUrl: "https://example.com/avatar/50.png",
      rating: 4,
      fullName: "Сергей Фомин",
      text: "Toyota Vios — очень хороший вариант для аренды. Мы арендовали её на Пхукете и остались довольны. Автомобиль в отличном состоянии, но иногда хотелось бы большей динамики. В целом, отличный выбор для города.",
    },
  ];

  const en: Review[] = [
    {
      id: "835122",
      carId: "019266fe-0883-7bb4-b7d7-90d3a9148306",
      avatarUrl: "https://example.com/avatar/101.png",
      rating: 4,
      fullName: "John Smith",
      text: "Rented this car in Phuket for island trips. Very convenient, easy to park in narrow spaces and quick on the winding roads. However, for long drives, I would appreciate a bit more comfort in the cabin.",
    },
    {
      id: "609187",
      carId: "019266fe-0883-7bb4-b7d7-90d3a9148306",
      avatarUrl: "https://example.com/avatar/202.png",
      rating: 5,
      fullName: "Michael Johnson",
      text: "Great car for rent in Phuket! Convenient for moving between beaches, spacious for all our belongings, and drives smoothly. Had no issues with all routes, including the mountain roads.",
    },
    {
      id: "485264",
      carId: "019266fe-0883-7bb4-b7d7-90d3a9148306",
      avatarUrl: "https://example.com/avatar/303.png",
      rating: 4,
      fullName: "Emily Davis",
      text: "We rented this car for a family vacation in Phuket. Everything was great: the car is fuel-efficient, has all the essentials, but I wish it had a bit more power on steep climbs.",
    },
    {
      id: "774326",
      carId: "019266fe-0883-7bb4-b7d7-90d3a9148306",
      avatarUrl: "https://example.com/avatar/404.png",
      rating: 5,
      fullName: "David Wilson",
      text: "Rented for three days for trips around Phuket. The car is perfect for small city trips and beach visits. No complaints, very comfortable and economical!",
    },
    {
      id: "301279",
      carId: "019266fe-0883-7bb4-b7d7-90d3a9148306",
      avatarUrl: "https://example.com/avatar/505.png",
      rating: 5,
      fullName: "Sophia Brown",
      text: "Wonderful car for a vacation in Phuket. We rented it for a week, and it handled any road perfectly, whether it was city streets or roads to remote beaches.",
    },
    //
    {
      id: "581255",
      carId: "019266fe-15ed-7aa5-a6ae-3d29548c2c28",
      avatarUrl: "https://example.com/avatar/101.png",
      rating: 5,
      fullName: "Emily Thompson",
      text: "Wonderful car for trips around Phuket. We rented it for a week, drove to beaches and up the mountains. Everything was perfect, very comfortable and reliable, especially loved the smooth ride on long stretches of road.",
    },
    {
      id: "773059",
      carId: "019266fe-15ed-7aa5-a6ae-3d29548c2c28",
      avatarUrl: "https://example.com/avatar/202.png",
      rating: 4,
      fullName: "Alexander Smith",
      text: "Rented a car in Phuket for city trips and visits to nearby villages. Convenient and maneuverable, but sometimes I wished for more power on the climbs. Overall, a great choice for rental.",
    },
    {
      id: "306276",
      carId: "019266fe-15ed-7aa5-a6ae-3d29548c2c28",
      avatarUrl: "https://example.com/avatar/303.png",
      rating: 5,
      fullName: "Maria Johnson",
      text: "The perfect car for rent in Phuket! We drove all over the island and had no issues with the vehicle. It handles both city streets and mountain roads easily. Highly recommended!",
    },
    {
      id: "962842",
      carId: "019266fe-26a4-7dda-b2fb-081f4408fe85",
      avatarUrl: "https://example.com/avatar/404.png",
      rating: 5,
      fullName: "Andrew Williams",
      text: "I rented the Toyota Yaris Cross in Phuket for island trips. The car is simply excellent! It handles local mountain roads effortlessly and has enough power for all climbs. Comfortable and easy to drive both in the city and on beach routes.",
    },
    {
      id: "481207",
      carId: "019266fe-26a4-7dda-b2fb-081f4408fe85",
      avatarUrl: "https://example.com/avatar/505.png",
      rating: 4,
      fullName: "Helen Brown",
      text: "We rented the Toyota Yaris Cross in Phuket for family trips. The car is spacious and economical, which we really liked. The only downside is the slightly stiff suspension on bumpy roads, but overall, it was a great experience.",
    },
    {
      id: "712904",
      carId: "019266fe-26a4-7dda-b2fb-081f4408fe85",
      avatarUrl: "https://example.com/avatar/606.png",
      rating: 5,
      fullName: "Maxim Davis",
      text: "The Toyota Yaris Cross turned out to be perfect for trips around Phuket. We rented it for a week, toured the whole island, and it performed excellently. Compact yet spacious inside, very convenient for navigating narrow streets and winding roads.",
    },
    {
      id: "395285",
      carId: "019266fe-26a4-7dda-b2fb-081f4408fe85",
      avatarUrl: "https://example.com/avatar/707.png",
      rating: 4,
      fullName: "Darya Lee",
      text: "We rented the Toyota Yaris Cross in Phuket and were very satisfied. The car drives excellently, especially enjoyed how it handles sharp turns. It would be ideal if it could handle road bumps a bit softer.",
    },
    //
    {
      id: "857194",
      carId: "019266fe-33ab-7229-b577-09da52f3d238",
      avatarUrl: "https://example.com/avatar/404.png",
      rating: 5,
      fullName: "Alex Grigoriev",
      text: "The Toyota Veloz is an excellent car for family trips around Phuket. We rented it for a few days, and it turned out to be incredibly spacious and comfortable. It handles winding roads well, with plenty of room for luggage and passengers. An ideal choice for a large family.",
    },
    {
      id: "649285",
      carId: "019266fe-33ab-7229-b577-09da52f3d238",
      avatarUrl: "https://example.com/avatar/505.png",
      rating: 4,
      fullName: "Irina Samoylova",
      text: "We rented the Toyota Veloz during our vacation in Phuket. The car is comfortable, with lots of space, especially for our shopping bags. The only downside was a bit more power needed on steep mountain roads, but overall, the car met our expectations.",
    },
    {
      id: "312099",
      carId: "019266fe-33ab-7229-b577-09da52f3d238",
      avatarUrl: "https://example.com/avatar/606.png",
      rating: 5,
      fullName: "Oleg Smirnov",
      text: "We rented the Toyota Veloz in Phuket for trips with friends. It's very spacious and perfect for driving around the island. It handles narrow streets easily, and everyone was satisfied. Plus, the car is new and in excellent condition!",
    },
    //
    {
      id: "486924",
      carId: "019266fe-496b-7bb9-9b3a-94730439c6d7",
      avatarUrl: "https://example.com/avatar/505.png",
      rating: 5,
      fullName: "James Smith",
      text: "The Toyota Fortuner is a gem for traveling around Phuket! We rented this SUV for a week, and it handled every road perfectly—from beaches to mountain trails. The cabin is very comfortable, and the engine has enough power for any conditions.",
    },
    {
      id: "729185",
      carId: "019266fe-496b-7bb9-9b3a-94730439c6d7",
      avatarUrl: "https://example.com/avatar/606.png",
      rating: 5,
      fullName: "Emily Johnson",
      text: "We were thrilled with the Toyota Fortuner! It's spacious, perfect for family trips around Phuket. It glides smoothly over bumpy roads, and we enjoyed traveling comfortably on both beaches and mountain roads. I definitely recommend it for rental.",
    },
    {
      id: "537621",
      carId: "019266fe-496b-7bb9-9b3a-94730439c6d7",
      avatarUrl: "https://example.com/avatar/707.png",
      rating: 4,
      fullName: "Michael Brown",
      text: "We took the Toyota Fortuner for our travels around Phuket, and it lived up to all our expectations. The car is powerful and reliable, easily tackling steep hills and rough terrain. The only downside was the fuel consumption, but that's normal for an SUV.",
    },
    {
      id: "198238",
      carId: "019266fe-5670-7aaf-b539-b4fa8ca11661",
      avatarUrl: "https://example.com/avatar/201.png",
      rating: 5,
      fullName: "Sophie Williams",
      text: "We rented a new 2023 Toyota Fortuner in Phuket—an incredibly comfortable and powerful car. We drove around the entire island, and there wasn't a single stretch of road that could stop it. The new interior with modern features is just fantastic!",
    },
    {
      id: "645821",
      carId: "019266fe-5670-7aaf-b539-b4fa8ca11661",
      avatarUrl: "https://example.com/avatar/301.png",
      rating: 5,
      fullName: "Daniel Johnson",
      text: "The latest 2023 Toyota Fortuner is top-notch! We took it for a trip around Phuket, and the car did not disappoint. It's very comfortable, with excellent suspension that easily handled the local roads. Convenient modern driver-assistance systems as well.",
    },
    {
      id: "731953",
      carId: "019266fe-5670-7aaf-b539-b4fa8ca11661",
      avatarUrl: "https://example.com/avatar/401.png",
      rating: 4,
      fullName: "Oliver Smith",
      text: "The 2023 Toyota Fortuner performed excellently on the roads of Phuket. It's a very powerful SUV, ideal for mountain curves and beaches. The only downside is the slightly high fuel consumption, but that's to be expected for such a powerful vehicle.",
    },
    //
    {
      id: "582941",
      carId: "019266fe-6242-7770-a53f-3f4e1b43a186",
      avatarUrl: "https://example.com/avatar/501.png",
      rating: 5,
      fullName: "James Taylor",
      text: "The 2022 Toyota Hilux is the perfect choice for adventures in Phuket! The four-door design provides plenty of room for passengers, and the powerful engine handles any road with ease. We drove through beaches and mountain trails—this truck never let us down!",
    },
    {
      id: "731005",
      carId: "019266fe-6242-7770-a53f-3f4e1b43a186",
      avatarUrl: "https://example.com/avatar/601.png",
      rating: 4,
      fullName: "Emma Wilson",
      text: "We rented the Toyota Hilux during our vacation in Phuket. The spacious interior was comfortable for the whole family. The truck easily handled steep climbs and rough roads. The only downside was its size; parking could be a bit tricky at times.",
    },
    {
      id: "894573",
      carId: "019266fe-6242-7770-a53f-3f4e1b43a186",
      avatarUrl: "https://example.com/avatar/701.png",
      rating: 5,
      fullName: "Liam Johnson",
      text: "The Toyota Hilux offers power and comfort in one package! The spacious four-door cabin was incredibly convenient for our group, and the vehicle's off-road capability surprised us—it easily tackled both beaches and rough terrains in Phuket. I highly recommend it for an active getaway.",
    },
    //
    {
      id: "348292",
      carId: "019266fe-6dfc-7669-8679-b73735fc4bb6",
      avatarUrl: "https://example.com/avatar/271.png",
      rating: 5,
      fullName: "Sophia Brown",
      text: "I rented the 2024 Honda Jazz during my vacation in Phuket, and I was absolutely thrilled! The car is very maneuverable and fuel-efficient. It's perfect for city driving and exploring the island. The interior is nice and modern, with everything in its place.",
    },
    {
      id: "249059",
      carId: "019266fe-6dfc-7669-8679-b73735fc4bb6",
      avatarUrl: "https://example.com/avatar/341.png",
      rating: 4,
      fullName: "Michael Smith",
      text: "The 2024 Honda Jazz turned out to be an excellent choice for trips around Phuket. It has a spacious interior for a small hatchback and a good trunk. The car is fast enough and easy to drive. The only downside is that it can be a bit noisy at high speeds.",
    },
    {
      id: "615084",
      carId: "019266fe-6dfc-7669-8679-b73735fc4bb6",
      avatarUrl: "https://example.com/avatar/121.png",
      rating: 5,
      fullName: "Olivia Davis",
      text: "I absolutely love the 2024 Honda Jazz! I rented it in Phuket, and it was the best decision ever. It's compact, economical, and has excellent handling. I appreciated the modern safety features and comfortable seats. I recommend it to anyone planning city trips!",
    },
    //
    {
      id: "415891",
      carId: "019266fe-7b7d-7bbd-888c-d6710e499c1e",
      avatarUrl: "https://example.com/avatar/751.png",
      rating: 5,
      fullName: "Emily Johnson",
      text: "I rented the 2024 Honda City in Phuket, and it exceeded all my expectations! The white color looks stunning, and the interior is clean and tidy. Excellent handling and fuel efficiency make it the perfect choice for city driving!",
    },
    {
      id: "382048",
      carId: "019266fe-7b7d-7bbd-888c-d6710e499c1e",
      avatarUrl: "https://example.com/avatar/901.png",
      rating: 4,
      fullName: "David Wilson",
      text: "The 2024 Honda City is very comfortable and stylish. We rented it in Phuket, and it handled all the local roads beautifully. The spacious interior and modern amenities made our trips very enjoyable. It's a bit noisy at speed, but overall, everything was great.",
    },
    {
      id: "563803",
      carId: "019266fe-7b7d-7bbd-888c-d6710e499c1e",
      avatarUrl: "https://example.com/avatar/441.png",
      rating: 5,
      fullName: "Liam Brown",
      text: "I am just thrilled with the Honda City! I rented it during my vacation in Phuket, and it was in excellent condition. Comfortable seats, good sound insulation, and modern technology make it the ideal car for traveling. I will definitely come back for it again!",
    },
    //
    {
      id: "724151",
      carId: "019266fe-86ad-7ee6-8574-8dbecc893f41",
      avatarUrl: "https://example.com/avatar/111.png",
      rating: 5,
      fullName: "Sophia Anderson",
      text: "I rented the 2024 Honda Accord in Phuket, and it was the best car for my vacation! It looks stylish and modern, and the interior is simply gorgeous. Very comfortable seats and plenty of space for luggage. This is the perfect vehicle for long trips around the island!",
    },
    {
      id: "842608",
      carId: "019266fe-86ad-7ee6-8574-8dbecc893f41",
      avatarUrl: "https://example.com/avatar/291.png",
      rating: 4,
      fullName: "Michael Taylor",
      text: "The 2024 Honda Accord is an excellent choice! I was really impressed with its performance and comfort. It handles the roads in Phuket beautifully. The only thing I would improve is a bit more space in the back seat. Other than that, everything was fantastic!",
    },
    {
      id: "593719",
      carId: "019266fe-86ad-7ee6-8574-8dbecc893f41",
      avatarUrl: "https://example.com/avatar/881.png",
      rating: 5,
      fullName: "Ava White",
      text: "Amazing car! The 2024 Honda Accord is simply magnificent. It's comfortable and quiet while driving. We traveled around Phuket, and it was a reliable companion. I highly recommend it for anyone looking to enjoy their trips without any worries!",
    },
    //
    {
      id: "473191",
      carId: "019266fe-91d2-7881-8a8d-2998ffbf7d59",
      avatarUrl: "https://example.com/avatar/371.png",
      rating: 5,
      fullName: "Emily Johnson",
      text: "I rented the 2024 Honda HR-V in Phuket, and it was an excellent choice! The car is stylish, comfortable, and very convenient for island trips. The high ground clearance makes it easy to navigate local roads. I recommend it to anyone looking for a reliable SUV!",
    },
    {
      id: "639583",
      carId: "019266fe-91d2-7881-8a8d-2998ffbf7d59",
      avatarUrl: "https://example.com/avatar/481.png",
      rating: 4,
      fullName: "David Brown",
      text: "The 2024 Honda HR-V turned out to be a great vehicle for exploring Phuket. It has a spacious interior and good trunk capacity. I liked the high seating position and excellent visibility. The suspension is a bit firm, but overall, it didn't ruin the experience.",
    },
    {
      id: "918303",
      carId: "019266fe-91d2-7881-8a8d-2998ffbf7d59",
      avatarUrl: "https://example.com/avatar/921.png",
      rating: 5,
      fullName: "James Smith",
      text: "Absolutely fantastic! The 2024 Honda HR-V is the perfect SUV for traveling around Phuket. The car was in excellent condition, packed with modern features, and had a comfortable interior. My family and I had a great time, and the HR-V was a reliable partner on the road!",
    },
    //
    {
      id: "392482",
      carId: "019266fe-9df5-777c-a3b5-c6ba339d131d",
      avatarUrl: "https://example.com/avatar/121.png",
      rating: 5,
      fullName: "Sophie Williams",
      text: "I rented the MG5 in Phuket, and it was the perfect companion for my vacation! The car looks very stylish, especially in white. The interior is comfortable and the handling is excellent. I loved every ride!",
    },
    {
      id: "824160",
      carId: "019266fe-9df5-777c-a3b5-c6ba339d131d",
      avatarUrl: "https://example.com/avatar/551.png",
      rating: 4,
      fullName: "Michael Johnson",
      text: "The MG5 is a great choice! It performed well in Phuket. Spacious and comfortable interior, plenty of room for luggage. However, I wished it had a bit more power for overtaking. Overall, I was very satisfied with the rental!",
    },
    {
      id: "467892",
      carId: "019266fe-9df5-777c-a3b5-c6ba339d131d",
      avatarUrl: "https://example.com/avatar/741.png",
      rating: 5,
      fullName: "Olivia Martinez",
      text: "What a fantastic car! The MG5 was in excellent condition and became a reliable friend during our time in Phuket. Stylish exterior and comfortable interior. I would definitely choose it again for island trips!",
    },
    {
      id: "579431",
      carId: "019266fe-9df5-777c-a3b5-c6ba339d131d",
      avatarUrl: "https://example.com/avatar/261.png",
      rating: 4,
      fullName: "Daniel Smith",
      text: "The MG5 is very stylish and modern. We rented it in Phuket and were pleased. Excellent handling and economical fuel consumption. The only downside was that I would have liked a more powerful engine for spirited driving.",
    },
    {
      id: "753211",
      carId: "019266fe-9df5-777c-a3b5-c6ba339d131d",
      avatarUrl: "https://example.com/avatar/831.png",
      rating: 5,
      fullName: "Charlotte Brown",
      text: "The MG5 was a real find during our vacation in Phuket! Stylish and modern, it attracted attention everywhere. Very easy to handle and perfect for island trips. I recommend it to everyone!",
    },
    //
    {
      id: "782302",
      carId: "019266fe-ab44-7bbe-acd8-e3776d5ae6f8",
      avatarUrl: "https://example.com/avatar/131.png",
      rating: 5,
      fullName: "Alex Johnson",
      text: "I rented the Mazda 2 in Phuket, and it was a fantastic choice! The car is very comfortable and perfect for city driving. Excellent handling and economical fuel consumption made our trips enjoyable. I recommend it to everyone!",
    },
    {
      id: "894562",
      carId: "019266fe-ab44-7bbe-acd8-e3776d5ae6f8",
      avatarUrl: "https://example.com/avatar/251.png",
      rating: 4,
      fullName: "Svetlana Nikiforova",
      text: "The Mazda 2 is an excellent city car! Convenient and compact, it handled local traffic very well. The only downside was a bit of a lack of power at high speeds, but overall, I had a positive experience.",
    },
    {
      id: "652135",
      carId: "019266fe-ab44-7bbe-acd8-e3776d5ae6f8",
      avatarUrl: "https://example.com/avatar/371.png",
      rating: 5,
      fullName: "Igor Mikhailov",
      text: "Our family rented the Mazda 2 for our vacation, and it was the best choice! Spacious interior, comfortable seats, and great sound system. We enjoyed driving to beautiful places in Phuket!",
    },
    {
      id: "312568",
      carId: "019266fe-ab44-7bbe-acd8-e3776d5ae6f8",
      avatarUrl: "https://example.com/avatar/491.png",
      rating: 4,
      fullName: "Olga Sergeeva",
      text: "I liked the Mazda 2 for its compactness and convenience. It was perfect for city trips in Phuket. The car was new and in excellent condition. I would have liked a bit more trunk space, but everything else was great!",
    },
    {
      id: "849321",
      carId: "019266fe-ab44-7bbe-acd8-e3776d5ae6f8",
      avatarUrl: "https://example.com/avatar/561.png",
      rating: 5,
      fullName: "Victoria Kovalenko",
      text: "A wonderful choice for rental! The Mazda 2 is very comfortable and stylish. We traveled around Phuket, and it handled the local roads perfectly. Very satisfied with the quality of the car!",
    },
    //
    {
      id: "473199",
      carId: "019266fe-b881-7550-9ff0-168bcbdc8cbf",
      avatarUrl: "https://example.com/avatar/141.png",
      rating: 5,
      fullName: "Anatoly Kuznetsov",
      text: "I rented the Mazda 3 in Phuket, and it was a fantastic choice! The white car looks stunning. It's comfortable, responds quickly to turns, and the handling is top-notch. I highly recommend it for island trips!",
    },
    {
      id: "298347",
      carId: "019266fe-b881-7550-9ff0-168bcbdc8cbf",
      avatarUrl: "https://example.com/avatar/671.png",
      rating: 4,
      fullName: "Elena Grigorieva",
      text: "The Mazda 3 is an excellent car for Phuket! It's comfortable and modern, and it holds the road very well. The only downside was wanting more space for rear passengers, but everything else was great!",
    },
    {
      id: "634830",
      carId: "019266fe-b881-7550-9ff0-168bcbdc8cbf",
      avatarUrl: "https://example.com/avatar/421.png",
      rating: 5,
      fullName: "Maxim Zaitsev",
      text: "Our family loved the Mazda 3! It’s a new car, very comfortable, with an excellent sound system. We enjoyed driving to beautiful places in Phuket, and we never regretted our choice.",
    },
    {
      id: "859431",
      carId: "019266fe-b881-7550-9ff0-168bcbdc8cbf",
      avatarUrl: "https://example.com/avatar/581.png",
      rating: 4,
      fullName: "Irina Vasilieva",
      text: "The Mazda 3 is a very stylish and comfortable car. It performed exceptionally well in Phuket. Great handling and economical fuel consumption. I wished for a bit more luggage space, but overall, it left a very good impression.",
    },
    {
      id: "194626",
      carId: "019266fe-b881-7550-9ff0-168bcbdc8cbf",
      avatarUrl: "https://example.com/avatar/711.png",
      rating: 5,
      fullName: "Roman Sidorov",
      text: "A fantastic car for rental! The Mazda 3 is perfect for trips around Phuket. It's beautiful, reliable, and comfortable. We encountered no issues during our use. I recommend it to everyone!",
    },
    {
      id: "614721",
      carId: "019266fe-c64d-7008-ad72-f66ba0fcb72c",
      avatarUrl: "https://example.com/avatar/191.png",
      rating: 5,
      fullName: "Kirill Smirnov",
      text: "We rented the Mazda CX-30 in Phuket, and it was an excellent choice! The red color of the car really stands out. It's very comfortable and powerful, making it perfect for traveling through the island's picturesque spots.",
    },
    {
      id: "128504",
      carId: "019266fe-c64d-7008-ad72-f66ba0fcb72c",
      avatarUrl: "https://example.com/avatar/221.png",
      rating: 4,
      fullName: "Maria Lebedeva",
      text: "The Mazda CX-30 left a good impression. It’s a great combination of style and comfort! It’s easy to handle, especially on the winding roads of Phuket. I wished for a bit more luggage space, but overall, I liked it.",
    },
    {
      id: "304893",
      carId: "019266fe-c64d-7008-ad72-f66ba0fcb72c",
      avatarUrl: "https://example.com/avatar/351.png",
      rating: 5,
      fullName: "Dmitry Solovyov",
      text: "My experience renting the Mazda CX-30 was amazing! The red color is just gorgeous. The car is new, fully functional, and has excellent safety features. We enjoyed driving around the island and visiting all the attractions.",
    },
    {
      id: "592105",
      carId: "019266fe-c64d-7008-ad72-f66ba0fcb72c",
      avatarUrl: "https://example.com/avatar/461.png",
      rating: 4,
      fullName: "Alexandra Fedorova",
      text: "The Mazda CX-30 is an excellent choice for trips around Phuket! Comfortable seats and a modern interior make the journey enjoyable. There were a few minor issues with the navigation, but overall, it didn’t spoil the experience.",
    },
    {
      id: "843921",
      carId: "019266fe-c64d-7008-ad72-f66ba0fcb72c",
      avatarUrl: "https://example.com/avatar/531.png",
      rating: 5,
      fullName: "Valentin Egorov",
      text: "The Mazda CX-30 is fantastic! We rented it for a week in Phuket and were completely thrilled. Beautiful appearance, excellent handling, and high fuel efficiency. I highly recommend it!",
    },
    //
    {
      id: "102938",
      carId: "019266fe-d711-788a-bfb9-ebe5d5ad8172",
      avatarUrl: "https://example.com/avatar/15.png",
      rating: 5,
      fullName: "Alexander Johnson",
      text: "We rented the BMW M5 in Phuket, and it was incredible! The white color of the car looks absolutely luxurious. Amazing power and handling. Every drive was a pleasure. Highly recommend!",
    },
    {
      id: "374821",
      carId: "019266fe-d711-788a-bfb9-ebe5d5ad8172",
      avatarUrl: "https://example.com/avatar/21.png",
      rating: 4,
      fullName: "Sophia Martinez",
      text: "The BMW M5 is a dream! We had an unforgettable time in Phuket. The only thing to note is that the suspension is quite stiff, but that's normal for a sports car. Everything else was top-notch!",
    },
    {
      id: "728106",
      carId: "019266fe-d711-788a-bfb9-ebe5d5ad8172",
      avatarUrl: "https://example.com/avatar/33.png",
      rating: 5,
      fullName: "Daniel Smith",
      text: "I can't express my excitement about the BMW M5! The white color makes it even more attractive. It's easy to handle, powerful engine, and excellent performance. Driving around Phuket was truly enjoyable!",
    },
    {
      id: "493272",
      carId: "019266fe-d711-788a-bfb9-ebe5d5ad8172",
      avatarUrl: "https://example.com/avatar/44.png",
      rating: 5,
      fullName: "Michael Brown",
      text: "This car is simply amazing! The BMW M5 is the epitome of style and speed. We drove all around Phuket and enjoyed every minute. I recommend it to anyone looking for unforgettable experiences!",
    },
    {
      id: "826511",
      carId: "019266fe-d711-788a-bfb9-ebe5d5ad8172",
      avatarUrl: "https://example.com/avatar/68.png",
      rating: 4,
      fullName: "Emma Wilson",
      text: "Renting the BMW M5 was a great choice for our vacation in Phuket. It’s an excellent car with high performance. However, keep in mind that the fuel consumption is above average. Overall, we were very satisfied!",
    },
    //
    {
      id: "102948",
      carId: "019266fe-e218-7556-862e-1a29c36d10d6",
      avatarUrl: "https://example.com/avatar/14.png",
      rating: 5,
      fullName: "James Anderson",
      text: "We rented the Toyota Vios in Phuket, and it was in excellent condition! It's the perfect choice for city driving. Compact size, economical fuel consumption, and comfortable ride. Very satisfied!",
    },
    {
      id: "294836",
      carId: "019266fe-e218-7556-862e-1a29c36d10d6",
      avatarUrl: "https://example.com/avatar/19.png",
      rating: 4,
      fullName: "Olivia Smith",
      text: "The Toyota Vios is a great rental car in Phuket! We were impressed with its condition. Comfortable and reliable. The only downside was that it lacked a bit of power on the highway, but it's just perfect for the city.",
    },
    {
      id: "832948",
      carId: "019266fe-e218-7556-862e-1a29c36d10d6",
      avatarUrl: "https://example.com/avatar/27.png",
      rating: 5,
      fullName: "William Johnson",
      text: "Wonderful experience renting the Toyota Vios! The car looked brand new, and driving it was easy and enjoyable. Perfect for exploring Phuket. I highly recommend it to anyone looking for a reliable and economical vehicle!",
    },
    {
      id: "583211",
      carId: "019266fe-e218-7556-862e-1a29c36d10d6",
      avatarUrl: "https://example.com/avatar/34.png",
      rating: 5,
      fullName: "Sophia Williams",
      text: "My husband and I rented the Toyota Vios for two weeks. The car was in excellent condition and fully functional. We enjoyed driving around Phuket and had a fantastic time. We will definitely come back!",
    },
    {
      id: "947264",
      carId: "019266fe-e218-7556-862e-1a29c36d10d6",
      avatarUrl: "https://example.com/avatar/41.png",
      rating: 4,
      fullName: "Liam Brown",
      text: "The Toyota Vios is a very good rental option. We rented it in Phuket and were satisfied. The car was in great condition, but sometimes I wished for a bit more dynamism. Overall, an excellent choice for the city.",
    },
  ];

  const all = {
    en,
    ru,
  };

  return all[locale].filter((review: Review) => {
    return review.carId === carId;
  });
};
